name = "Barbaric Optimism"
author = "Barbaric Huo Optimism"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18cea611f8daee384f26d98a17c221fffbd15e86869337da5c4d16ddd31756c2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.231"
