name = "Barbaric Optimism"
author = "Barbaric Huo Optimism"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b5c2852c59bfd81f9de277431518c6403fc5913958c0a5e57016c3ce5ee790c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.231"
