name: Deploy

on:
  push:
    branches: [ "dev", "main" ]

  workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
            ref: dev
            path: 'dev'


      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
            ref: main
            path: 'main'

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: true
          cache-dependency-path: ''

      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Packwiz Refresh (dev)
        run: |
          cd dev
          packwiz refresh --build
      - name: Packwiz Refresh (main)
        run: |
          cd main
          packwiz refresh --build
    
      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
            path: '.'

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4